name: Booky
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  image_picker: ^0.2.1
  url_launcher: "^2.0.1"
  googleapis: any
  googleapis_auth: any
  share: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/book.jpg

